language: node_js
node_js:
  - "lts/*"

cache:
  directories:
    - node_modules
script:
  - yarn
  - yarn add coveralls
  - yarn test -- -u --coverage 
  - jest --maxWorkers=2
after_success:
  - npm run coveralls